/* Generated by Edge Impulse
 * Copyright (c) 2022 EdgeImpulse Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef _EI_CLASSIFIER_ANOMALY_TYPES_HEADER_H_
#define _EI_CLASSIFIER_ANOMALY_TYPES_HEADER_H_

#define EI_CLASSIFIER_HAS_ANOMALY    1

const uint16_t EI_CLASSIFIER_ANOM_AXIS[]  { 0, 11, 22 };
#define EI_CLASSIFIER_ANOM_AXIS_SIZE      3
#define EI_CLASSIFIER_ANOM_CLUSTER_COUNT  32

typedef struct {
float centroid[EI_CLASSIFIER_ANOM_AXIS_SIZE];
float max_error;
} ei_classifier_anom_cluster_t;

#endif // _EI_CLASSIFIER_ANOMALY_TYPES_HEADER_H_
